# Form implementation generated from reading ui file 'add-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtWidgets
import json, os

class CreateNewApp:
    def __init__(self, appOrGame, appPicture, appName, appRating, appDownloadLink, appDescription, appCategory, appVersion=None, appRequirement=None, appSize=None):
        self.appOrGame = appOrGame
        self.appPicture = appPicture
        self.appName = appName
        self.appRating = appRating
        self.appDownloadLink = appDownloadLink
        self.appDescription = appDescription
        self.appCategory = appCategory
        self.appVersion = appVersion
        self.appRequirement = appRequirement
        self.appSize = appSize

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(375, 390)
        Form.setStyleSheet("background: gray;")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 341, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appOrGame = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.appOrGame.setCurrentText("")
        self.appOrGame.setObjectName("appOrGame")
        self.appOrGame.addItem("")
        self.appOrGame.addItem("")
        self.appOrGame.addItem("")
        self.verticalLayout.addWidget(self.appOrGame)
        self.appPicture = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appPicture.setText("")
        self.appPicture.setObjectName("appPicture")
        self.verticalLayout.addWidget(self.appPicture)
        self.appName = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appName.setText("")
        self.appName.setObjectName("appName")
        self.verticalLayout.addWidget(self.appName)
        self.appRating = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appRating.setObjectName("appRating")
        self.verticalLayout.addWidget(self.appRating)
        self.appDownloadLink = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appDownloadLink.setObjectName("appDownloadLink")
        self.verticalLayout.addWidget(self.appDownloadLink)
        self.appDescription = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appDescription.setStyleSheet("")
        self.appDescription.setObjectName("appDescription")
        self.verticalLayout.addWidget(self.appDescription)
        self.appCategory = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.appCategory.setStyleSheet("")
        self.appCategory.setObjectName("appCategory")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.appCategory.addItem("")
        self.verticalLayout.addWidget(self.appCategory)
        self.appVersion = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appVersion.setObjectName("appVersion")
        self.verticalLayout.addWidget(self.appVersion)
        self.appRequirement = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appRequirement.setObjectName("appRequirement")
        self.verticalLayout.addWidget(self.appRequirement)
        self.appSize = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appSize.setObjectName("appSize")
        self.verticalLayout.addWidget(self.appSize)
        self.addButton = QtWidgets.QPushButton(parent=Form)
        self.addButton.setGeometry(QtCore.QRect(290, 360, 75, 24))
        self.addButton.setObjectName("addButton")
        self.addButton.clicked.connect(self.add)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def add(self):
        appOrGame_index = self.appOrGame.currentIndex()
        appOrGame = self.appOrGame.itemText(appOrGame_index)
        appPicture = self.appPicture.text()
        appName = self.appName.text()
        appRating = self.appRating.text()
        appDownloadLink = self.appDownloadLink.text()
        appDescription = self.appDescription.text()
        appCategory_index = self.appCategory.currentIndex()
        appCategory = self.appCategory.itemText(appCategory_index)
        appVersion = self.appVersion.text()
        appRequirement = self.appRequirement.text()
        appSize = self.appSize.text()
        NewApp = CreateNewApp(appOrGame=appOrGame,
                            appPicture=appPicture,
                            appName=appName,
                            appRating=appRating, 
                            appDownloadLink=appDownloadLink, 
                            appDescription=appDescription, 
                            appCategory=appCategory, 
                            appVersion=appVersion, 
                            appRequirement=appRequirement, 
                            appSize=appSize)
        dic = NewApp.__dict__
        # print(dic)

        directory_path = r'.\Bulaloi-App-Development-Experiment\next-app\public\apps-games-data\apps'

        filename = appName + ".json"

        full_path = os.path.join(directory_path, filename)

        with open(full_path, 'w') as file:
            json.dump(dic, file, indent=4)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add"))
        self.appOrGame.setPlaceholderText(_translate("Form", "App or Game"))
        self.appOrGame.setItemText(0, _translate("Form", "App or Game"))
        self.appOrGame.setItemText(1, _translate("Form", "Game"))
        self.appOrGame.setItemText(2, _translate("Form", "App"))
        self.appPicture.setPlaceholderText(_translate("Form", "App Image URL"))
        self.appName.setPlaceholderText(_translate("Form", "App Name"))
        self.appRating.setPlaceholderText(_translate("Form", "App Rating 1 to 5"))
        self.appDownloadLink.setPlaceholderText(_translate("Form", "appDownloadLink"))
        self.appDescription.setPlaceholderText(_translate("Form", "appDescription"))
        self.appCategory.setPlaceholderText(_translate("Form", "Category"))
        self.appCategory.setItemText(0, _translate("Form", "Game Category"))
        self.appCategory.setItemText(1, _translate("Form", "Role-playing"))
        self.appCategory.setItemText(2, _translate("Form", "FPS"))
        self.appCategory.setItemText(3, _translate("Form", "Adventure"))
        self.appCategory.setItemText(4, _translate("Form", "Action"))
        self.appCategory.setItemText(5, _translate("Form", "Casual"))
        self.appCategory.setItemText(6, _translate("Form", "Arcade"))
        self.appCategory.setItemText(7, _translate("Form", "App Category"))
        self.appCategory.setItemText(8, _translate("Form", "Phone editor"))
        self.appCategory.setItemText(9, _translate("Form", "Task-app Management"))
        self.appCategory.setItemText(10, _translate("Form", "Video player & Editor"))
        self.appCategory.setItemText(11, _translate("Form", "Music"))
        self.appCategory.setItemText(12, _translate("Form", "Productivity"))
        self.appVersion.setPlaceholderText(_translate("Form", "appVersion"))
        self.appRequirement.setPlaceholderText(_translate("Form", "appRequirement"))
        self.appSize.setPlaceholderText(_translate("Form", "appSIze"))
        self.addButton.setText(_translate("Form", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
