# Form implementation generated from reading ui file 'edit-window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(375, 390)
        Form.setStyleSheet("background: gray;")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 341, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.appOrGame = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.appOrGame.setCurrentText("")
        self.appOrGame.setObjectName("appOrGame")
        self.appOrGame.addItem("")
        self.appOrGame.addItem("")
        self.appOrGame.addItem("")
        self.verticalLayout.addWidget(self.appOrGame)
        self.appPicture = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appPicture.setText("")
        self.appPicture.setObjectName("appPicture")
        self.verticalLayout.addWidget(self.appPicture)
        self.appName = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appName.setText("")
        self.appName.setObjectName("appName")
        self.verticalLayout.addWidget(self.appName)
        self.appRating = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appRating.setObjectName("appRating")
        self.verticalLayout.addWidget(self.appRating)
        self.appDownloadLink = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appDownloadLink.setObjectName("appDownloadLink")
        self.verticalLayout.addWidget(self.appDownloadLink)
        self.appDescription = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appDescription.setStyleSheet("")
        self.appDescription.setObjectName("appDescription")
        self.verticalLayout.addWidget(self.appDescription)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.verticalLayoutWidget)
        self.comboBox_2.setStyleSheet("")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.appVersion = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appVersion.setObjectName("appVersion")
        self.verticalLayout.addWidget(self.appVersion)
        self.appRequirement = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appRequirement.setObjectName("appRequirement")
        self.verticalLayout.addWidget(self.appRequirement)
        self.appSize = QtWidgets.QLineEdit(parent=self.verticalLayoutWidget)
        self.appSize.setObjectName("appSize")
        self.verticalLayout.addWidget(self.appSize)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(290, 360, 75, 24))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add"))
        self.appOrGame.setPlaceholderText(_translate("Form", "App or Game"))
        self.appOrGame.setItemText(0, _translate("Form", "App or Game"))
        self.appOrGame.setItemText(1, _translate("Form", "Game"))
        self.appOrGame.setItemText(2, _translate("Form", "App"))
        self.appPicture.setPlaceholderText(_translate("Form", "App Image URL"))
        self.appName.setPlaceholderText(_translate("Form", "App Name"))
        self.appRating.setPlaceholderText(_translate("Form", "App Rating 1 to 5"))
        self.appDownloadLink.setPlaceholderText(_translate("Form", "appDownloadLink"))
        self.appDescription.setPlaceholderText(_translate("Form", "appDescription"))
        self.comboBox_2.setPlaceholderText(_translate("Form", "Category"))
        self.comboBox_2.setItemText(0, _translate("Form", "Category"))
        self.comboBox_2.setItemText(1, _translate("Form", "Adventure"))
        self.comboBox_2.setItemText(2, _translate("Form", "Action"))
        self.comboBox_2.setItemText(3, _translate("Form", "Casual"))
        self.comboBox_2.setItemText(4, _translate("Form", "Arcade"))
        self.appVersion.setPlaceholderText(_translate("Form", "appVersion"))
        self.appRequirement.setPlaceholderText(_translate("Form", "appRequirement"))
        self.appSize.setPlaceholderText(_translate("Form", "appSIze"))
        self.pushButton.setText(_translate("Form", "Add"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
